### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by matle85** [bitshares/awesome-bitshares#10]
Just flagging that the following are down as of today (not saying they should be removed but maybe highlighting as a 'watch list'):

https://bits.farm/en/
http://www.btsabc.org/
https://eubx.io/ - website is there but when you click on exchange it just directs you to T&Cs (dead end?)
https://cryptrade.io/
https://www.dynx.io/ - still down ahead of mainnet launch but may not mean anything
https://www.hellobts.com/ 
https://exchange.winex.pro/

**Comment by Agorise** [comment]
I think you can close this issue now, @matle85 :) 
We have updated the /awesome-bitshares readme.

**Comment by matle85** [comment]
Looks like there might be a new addition with WALLDEX coming in as well :D
