### ISSUE TITLE
Add new NFT resources

### ISSUE THREAD

**Issue by grctest** [bitshares/awesome-bitshares#102]
The following tools are MIT open sourced & enable issuing and viewing NFTs on the Bitshares blockchain:
https://github.com/BTS-CM/nft_tool
https://github.com/BTS-CM/NFT_Viewer

**Comment by abitmore** [comment]
Created https://github.com/bitshares/awesome-bitshares/pull/103. What do you think?

**Comment by grctest** [comment]
Looks good to me 👍
