### ISSUE TITLE
I think we need to creat a discord channel

### ISSUE THREAD

**Issue by shulthz** [bitshares/awesome-bitshares#59]
I think we need to creat a new discord channel, the old one has been destroyed.
https://discord.com/

This is Basis project discord channel:
https://discord.gg/NU2G2jrByq

**Comment by abitmore** [comment]
Just do it.

**Comment by shulthz** [comment]
I have creat one, anyone can jump in:

https://discord.gg/Fp3ArHWkYN

**Comment by abitmore** [comment]
Someone created another one: https://discord.gg/ScAVzFHG

**Comment by abitmore** [comment]
I don't use Discord, I guess this one managed by fav is good? https://discord.com/invite/GsjQfAJ

**Comment by shulthz** [comment]
> 
> 
> I don't use Discord, 

Discord is more better for a project than telegram, didn't need so many different telegram group.
