### ISSUE TITLE
https://www.compumatrix.co/?

### ISSUE THREAD

**Issue by shulthz** [bitshares/awesome-bitshares#63]
https://www.compumatrix.co/?

https://www.compumatrix.ph/2020/10/25/compumatrix-origins-part-1/

**Comment by abitmore** [comment]
See #36

**Comment by abitmore** [comment]
@shulthz if you got useful info please reply in that pull request. Thanks.

**Comment by shulthz** [comment]
> 
> 
> @shulthz if you got useful info please reply in that pull request. Thanks.

No useful info, they just allow their members come in...no clue...
