### ISSUE TITLE
Add: Listing of Public Kibana Endpoints

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/awesome-bitshares#9]
As a user I want a list of public Kibana endpoints to query blockchain data and perform visualizations.

Note: API Servers are listed within the the UI repository to support the reference wallet. However, I am not aware of a listing for Kibana (elasticsearch frontend) endpoints.

**Comment by Agorise** [comment]
All ES servers are down right now due to the expense, so I guess Kibana is down as well.

**Comment by abitmore** [comment]
This has been done.
